[build]
  # Tentukan perintah untuk menjalankan aplikasi
  entrypoint = "python GeminiDiscordBot.py"

[variables]
  DISCORD_BOT_TOKEN = "@your_discord_bot_token"
  GOOGLE_AI_KEY = "@your_google_ai_key"
  MAX_HISTORY = "@your_max_history_value"
